name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install swiftlint
      run: brew install swiftlint
    - name: run swiftlint
      run: swiftlint
