name: CI

on: pull_request

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install danger
      run: bundle install
    - name: install swiftlint
      run: brew install swiftlint
    - name: run danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: danger
